[phases.setup]
nixPkgs = ['libgl', 'glib', 'libsm', 'libxext', 'libfontconfig', 'libxrender', 'gomp', 'enchant2']

[phases.install]
cmds = ['pip install -r requirements.txt']

[start]
cmd = 'gunicorn --bind 0.0.0.0:$PORT app:app'
